blueprint:
  name: Aqara D1 Wireless Remote Switch (Double)
  description: Add support D1 with original Xiaomi Gateway 3
  domain: automation
  source_url: https://github.com/ZeroKing666/HS-Blueprints
  input:
    remote:
      name: Remote
      description: Action Sensor Aqara
      selector:
        entity:
          integration: xiaomi_gateway3
          domain: sensor
    condition:
      name: Condition
      description: Condition to test before handling a button press
      default: []
      selector:
        action:
    left_click:
      name: Left Click
      default: []
      selector:
        action:
    left_double:
      name: Left Double
      default: []
      selector:
        action:
    left_long:
      name: Left Long
      default: []
      selector:
        action:
    right_click:
      name: Right Click
      default: []
      selector:
        action:
    right_double:
      name: Right Double
      default: []
      selector:
        action:
    right_long:
      name: Right Long
      default: []
      selector:
        action:
    both_click:
      name: Both Click
      default: []
      selector:
        action:
    both_double:
      name: Both Double
      default: []
      selector:
        action:
    both_long:
      name: Both Long
      default: []
      selector:
        action:

mode: restart
max_exceeded: silent

trigger:
  platform: state
  entity_id: !input remote
  attribute: action

condition: !input condition

action:
  - variables:
      command: "{{ trigger.to_state.state }}"
  - choose:
      - conditions: "{{ command == 'button_1_single' }}"
        sequence: !input left_click

      - conditions: "{{ command == 'button_1_double' }}"
        sequence: !input left_double

      - conditions: "{{ command == 'button_1_hold' }}"
        sequence: !input left_long

      - conditions: "{{ command == 'button_2_single' }}"
        sequence: !input right_click

      - conditions: "{{ command == 'button_2_double' }}"
        sequence: !input right_double

      - conditions: "{{ command == 'button_2_hold' }}"
        sequence: !input right_long

      - conditions: "{{ command == 'button_both_single' }}"
        sequence: !input both_click

      - conditions: "{{ command == 'button_both_double' }}"
        sequence: !input both_double

      - conditions: "{{ command == 'button_both_hold' }}"
        sequence: !input both_long
