blueprint:
  name: Door Sensor-activated switch
  description: Turn on a switch when door is opened after sunset.
  source_url: https://github.com/ZeroKing666/HS-Blueprints
  domain: automation
  input:
    doorsensor_entity:
      name: Door Sensor
      selector:
        entity:
          domain: binary_sensor
    light_target:
      name: Switch
      selector:
        target:
          entity:
            domain: switch
    door_closed_wait:
      name: Wait time
      description: Time to leave the switch on after door is closed
      default: 120
      selector:
        number:
          min: 0.0
          max: 3600.0
          unit_of_measurement: seconds
          mode: slider
          step: 1.0
mode: single
max_exceeded: silent
trigger:
  platform: state
  entity_id: !input 'doorsensor_entity'
  from: 'off'
  to: 'on'
condition:
- condition: state
  entity_id: sun.sun
  state: below_horizon
action:
- service: switch.turn_on
  target: !input 'light_target'
- wait_for_trigger:
    platform: state
    entity_id: !input 'doorsensor_entity'
    from: 'on'
    to: 'off'
- delay: !input 'door_closed_wait'
- service: switch.turn_off
  target: !input 'light_target'
